default:
  image: node

stages:
  - build_deploy

build:
  stage: build_deploy
  image: docker:19.03.12
  services:
    - docker:dind
  script:
    - docker build 
      --build-arg SECRET="$SECRET" 
      --build-arg PORT="$APP_PORT" 
      --build-arg PG_HOST="$PG_HOST" 
      --build-arg PG_PORT="$PG_PORT" 
      --build-arg PG_USERNAME="$PG_USERNAME" 
      --build-arg PG_PASSWORD="$PG_PASSWORD" 
      --build-arg PG_DATABASE="$PG_DATABASE" 
      --build-arg PG_SSL=true 
      -t "$ACR_REPOSITORY"/keskuskauppa-app .
    - docker login "$ACR_REPOSITORY"
      --username "$ACR_USERNAME"
      --password "$ACR_PASSWORD"
    - docker push "$ACR_REPOSITORY/keskuskauppa-app:latest"
